function [linepixel2latlon, latlon2linepixel]=geo_trans(sar_struct)

latlonPoints= ...
    [sar_struct.geo_info(1).lat sar_struct.geo_info(1).lon;...
    sar_struct.geo_info(2).lat sar_struct.geo_info(2).lon;...
    sar_struct.geo_info(3).lat sar_struct.geo_info(3).lon];
linepixelPoints = ...
    [sar_struct.geo_info(1).x sar_struct.geo_info(1).y;...
    sar_struct.geo_info(2).x sar_struct.geo_info(2).y;...
    sar_struct.geo_info(3).x sar_struct.geo_info(3).y];

linepixel2latlon = fitgeotrans(linepixelPoints,latlonPoints,'affine');
latlon2linepixel = fitgeotrans(latlonPoints,linepixelPoints,'affine');

end